### PR TITLE
Better registration wizard

### PR DESCRIPTION
**Pull request by iasoon**
TODO:
- [x] The style of the buttons to choose between ISIC and FK does not really fit the application style, it would be nice to have them as the same style from the a's in option-choosers
- [x] add some text why people could also choose for FK cards
- [x] Extra attribute questions are not displayed in the info form, yet their validations are triggered. This should only happen at the next step => To solve this, a member should have a `status` in the database with the same name as the different wizard steps. Validations can then be made depended on this state. See http://www.schneems.com/post/21267434507/partial-validation-of-active-record-objects-in-wicked/ for example. This avoids hacking into the validation model code...
- [x] check FKBooks redirect
- [x] check out the session stuff
- [x] taking pictures in front end with webcam does not popup anything
- [x] For some reason, scriptcam.lic gets requested resulting in Wicked crashing from an `Wicked::Wizard::InvalidStepError` when clicking the "take a webcam picture" button:
```
Started GET "/chemica/registration/scriptcam.lic" for ::1 at 2015-08-30 16:53:53 +0200
```
- [x] adding pictures does not work: it redirects to `success` instead of asking me to crop my picture related to the `@member.photo_valid?` stuff
- [x] check out the empty if
- [x] check out why the extra attributes page isn't shown anymore
- [x] add a column to the backend table to show if a member has registered for an isic card or not
- [x] fix tests
- [x] fix scriptcamshizzle
- [x] add modifiable FK-card text instead of ISIC card
- [x] switch FK order

### CODE REVIEW

**Comment by Silox** [comment]
Some issues
- [ ] The style of the buttons to choose between ISIC and FK does not really fit the application style, it would be nice to have them as the same style from the a's in option-choosers
- [ ] Extra attribute questions are not displayed in the form, although their validations get triggered

**Comment by Silox** [comment]
I don't like the hacky approach way to remove errors from validated fields from steps in the future. Check out http://www.schneems.com/post/21267434507/partial-validation-of-active-record-objects-in-wicked/ for a decent way to implement this.

**Comment by Silox** [comment]
What happens to the session if someone decides to back away from the computer mid-registration, and lets someone else register for a club?

**Comment by iasoon** [comment]
In reply to your last comment: The user data stored in the session gets deleted when restarting the process or completing it. 

This way, your concern would be no different from someone filling in half of his info on one monolithic registration page, and just leaving.

**Pull request merged**
